import React from 'react'
import "./privacypolicy.css"
import Haveidea from '../haveIdeacard/Haveidea'

const Privacypolicy = () => {


    return (
        <>
            <div className="conatiner-fluid termMain pb-5">
                <div className="container ">
                    <div className="privacyHeading">
                    <h2 className="terms-title ">Privacy &amp; Policy</h2>
                    </div>
                   
                       
                                <div className="privacy-container">
                                    <div className="privacyText">
                                        <p>  <a className='anchorPrivacy'  href="/"><span className="first-letter"> v</span>ervebot.io</a> (“VerveBot,” “we,” or “us”) respects your privacy and is committed to protecting it. This Privacy Policy (“Policy”) describes how we handle information about you that we collect on our websites and related mobile applications (collectively, “Website” or “Site”), through our loyalty programs, through our technology that others may use, and from other sources. Your continued activity on this Website and/or in our loyalty programs indicates your acceptance of this Policy. If you have any objections to this Policy, you should immediately discontinue use of the Website and/or participation in our loyalty programs.</p><p>Data We Collect</p>
                                        <p>We may collect different types of data from or about you, which data may include:</p>
                                        <p>Information you provide. We may collect data from you such as your name, email address, street address, postal code, age, telephone number, driver’s license number (e.g. if you request check acceptance privileges at our member or subsidiary stores), purchase history, biometric data, employment history (e.g. if you submit an employment application) and credit card information when you provide it to us, such as when you:<br />contact us via the Website<br />sign up to receive e-mails from us<br />create a personal shopping list or save recipes<br />request a rebate<br />enter a contest<br />download or use on-line coupons or mobile coupons<br />download or use an app<br />overview circulars and manage shopping lists<br />place an online order<br />submit a job application<br />apply for check cashing privileges<br />Aggregated, anonymized or de-identified data. Our collection, use, and disclosure of aggregated, anonymized or de-identified data is not restricted by this Policy because it cannot identify you as an individual.<br />Information about your online activity. We may collect data about your activity on the Website and our mobile applications, including but not limited to your IP address, device-specific information and geolocation information, by using various online tracking technologies. These are explained further below.<br />Information from other sources. We may collect data about you from our affiliates, partners or third parties, including but not limited to consumer research firms and public databases, for the purposes enumerated below, and/or to supplement information we already possess.</p>
                                        <p>How We Use and Share Data</p>
                                        <p>We use data in different ways including the following:</p>
                                        <p>To process and manage your purchases, transactions, and payments with us.<br />To respond to your questions, suggestions, and comments.<br />To provide product recall information.<br />To monitor and improve our Website functionality.<br />To provide coupons and personalize your Website experience.<br />For operational or business purposes.<br />To help improve your customer experience in stores or online.<br />To provide you with information we think may be of interest to you.<br />To provide you with advertisements or offers relevant to you based on your interests, purchase history, or other criteria. This type of interest-based advertising may use information collected from your online behavior across multiple websites that you visit, or across multiple devices you may use, in order to predict your preferences. You can learn more about it by visiting the Network Advertising Initiative’s (NAI) website at networkadvertising.org or the Digital Advertising Alliance (DAA) website at www.digitaladvertisingalliance.org.<br />To detect security incidents and other fraudulent activity.<br />To help maintain the safety, security, and integrity of our Website, products and services, databases, and other technology assets, and business.</p>
                                        <p>We may share data with the following parties:</p>
                                        <p>With VerveBot members, subsidiaries, affiliates and related companies;<br />With third-party service providers (e.g. Website developers and hosts, payment vendors) who process the information for the purpose of operating the Website or rendering the requested service (e.g., online checkout) to you;<br />With third-party service providers for research or survey purposes, such as communicating with you regarding your customer experience;<br />With VerveBot product vendors for such vendors’ accessing of sales data of the vendors’ products;<br />With third parties who may use the data to serve you ads or provide you with information on offers relevant to you based on your interests, purchase history, or other criteria; and<br />With any other parties not identified above so long as the data we share is aggregated, anonymized or de-identified such that it does not identify you as an individual.</p>
                                        <p>We may also share data in the following special circumstances:</p>
                                        <p>When we believe that the disclosure is reasonably necessary to comply with applicable laws, regulations, legal processes, or requests from law enforcement or regulatory authorities.<br />To prevent, detect or otherwise handle fraud, security, or technical issues.<br />To protect the safety, rights, or property of any person or the public.<br />If VerveBot ever undergoes a business acquisition, merger, sale or change of control.</p>
                                        <p>Third-Party Services on the Site</p>
                                        <p>Certain areas on this Website may allow for data collection by third parties to perform certain activities or fulfill your requests, such as online checkout, payment processing, shopping list management, digital coupon fulfillment, or grocery delivery. When you provide your data in these areas, collection, use and disclosure of your data is by the service provider and therefore subject to the service provider’s privacy policy, which you should review before providing your data.</p>
                                        <p>Links to Third-Party Websites on the Site</p>
                                        <p>The Website may also contain links to websites owned by third parties. You understand, acknowledge and agree that these links are provided solely as a convenience to you and not as an endorsement by VerveBot of any third-party content, advertising or business practices. VerveBot is not responsible for the privacy practices or the content on any of the linked websites, including any websites that may indicate a special relationship or “partnership” with VerveBot. Collection of your data by the linked websites is outside the control of VerveBot. Review all third-party privacy policies carefully.</p>
                                        <p>Third Party Advertisers</p>
                                        <p>Third party ad servers or ad networks may display advertisements on the Site. When you click on the ad, your IP address will be received automatically by the ad server, using technologies that may include cookies, JavaScript and web beacons to personalize the ad content and to evaluate the effectiveness of the ads. We recommend that you review the privacy policies of our third party advertisers, for which we are not responsible. Our Privacy Policy does not apply to, and we cannot control the activities of, third party advertisers.</p>
                                        <p>Technology Tracking</p>
                                        <p>We and/or our service providers may use a variety of tracking technologies, such as session and persistent cookies, web beacons, clear gifs, session IDs, successor tracker technology and other similar technologies as you navigate the Site. “Cookies,” for instance, are small text files placed on your Internet browser in order to perform functions like tracking your preferences and selections as you navigate the Site, showing you advertisements based on your interests, or gathering information about the technology you are using to access the Site. We passively collect this information for many purposes, including to understand what areas of the Site are most popular, which areas may require improvement and what technologies are being used by our visitors. This information helps us to update and improve the Site. We may also use this information for security purposes, to detect and to block security breaches and to provide you with a safe online environment. We reserve the right to use, and to permit our service providers to use, these tracking technologies, as well as other comparable or future technologies, to collect information.</p>
                                        <p>Physical Location</p>
                                        <p>When you download our mobile applications, we may use and store GPS information relating to your mobile device, in combination with other location-based information such as your IP address, your billing postal code provided by your carrier, or your registration location, to provide enhanced location-based services, and to serve location-targeted advertising, search results, and other content.</p>
                                        <p>Procedures to Review Your Personal Data and to Opt-Out of Communications</p>
                                        <p>With respect to data covered by this Policy (i.e. not aggregated, anonymized or de-identified data), please contact VerveBot Customer Care service team at VerveBot if you wish to review any personal data we may have about you. Please provide our Customer Care representatives with the specific categories of data you are requesting (e.g., contact information, payment information, etc.), and if we possess that information, we will provide you with a readable copy of such data at no charge. Factual errors in your personal data, including out-of-date information, can be corrected by sending us a request that credibly shows our error. To protect your privacy and security, we take commercially reasonable steps to verify your identity before granting access to data or making corrections.</p>
                                        <p>Also, you may always opt-out of receiving communications from us. If you do not want your data to be shared with third parties in the manner discussed in this Privacy Policy, please contact us using the information in the “Contact Us” section.</p>
                                        <p>If you are receiving e-mail messages from us and do not wish to receive any more, use the links on the bottom of the e-mail message to make changes to your e-mail preferences. If there are no links, follow the instructions at the bottom of the message. When we receive your notification that you want to opt-out, we will process your request as soon as possible. Please note, however, that if you direct us not to share your personal data, you may not be eligible for certain loyalty program promotions that require your data.</p>
                                        <p>Security of Information</p>
                                        <p>The data collected through the Website is maintained by us and/or our service providers in a manner consistent with applicable laws.</p>
                                        <p>Unfortunately, no data transmission over the Internet or any wireless network can be guaranteed to be 100% secure. As a result, while we strive to protect your data, you acknowledge that:<br />(a) there are security and privacy limitations of the Internet which are beyond our control; (b) the security, integrity, and privacy of any and all information and data exchanged between you and us through the Website cannot be guaranteed; (c) any such information and data may be viewed or tampered with in transit by a third party; and (d) WHEN YOU TRANSFER ANY INFORMATION TO US, YOU DO SO AT YOUR OWN RISK. YOU ARE RESPONSIBLE AT ALL TIMES FOR MAINTAINING THE CONFIDENTIALITY OF ANY PASSWORD OR OTHER ACCESS INFORMATION.</p>
                                        <p>International Users</p>
                                        <p>The Website is hosted in the United States and intended for use in the U.S. If you are accessing the Website from a location outside the U.S. and that location has laws or regulations regarding the collection, use and/or disclosure of data that is different than U.S. laws and regulations, please be advised that your continued use of the Website, which is governed by U.S. law (as stated in the Terms &amp; Conditions), indicates your consent to the transfer of your data to the U.S.</p>
                                        <p>Children</p>
                                        <p>Protecting the privacy of the very young is especially important. We never collect or maintain information at the Website from persons we know to be under age 13. Please do not communicate with or contact us if you are under age 13. By your participation in our Website activities, you certify that you are at least 13 years of age and meet all other eligibility requirements of the Website. If we learn that data relating to someone under the age of 13 has been collected on the Website, we will take appropriate steps to delete such information.</p>
                                        <p>Changes to this Policy</p>
                                        <p>Grocerywala may revise this Privacy Policy over time as new features are added to the Website or as Internet law and standards evolve, and this will be reflected by the “Last Modified” notice below. We will post those changes prominently but we do recommend that you read this Policy periodically when you visit the Website.</p>
                                        <p>CONTACT US: For questions or concerns relating to this Policy or your privacy generally, or to exercise your rights as described in this Policy, please visit the customer service desk in any of our member or subsidiary stores, use the “Contact Us” page on this Site, or contact VerveBot’s Customer Care service team at info@34.203.234.180</p>
                                    </div>
                                </div>
                            </div>
                      
                  
                    <Haveidea />

                </div>
            {/* </div> */}
        

        </>
    )
}

export default Privacypolicy